source 'https://rubygems.org'

ruby '3.2.2'

gem 'dotenv-rails', groups: [:development, :test]
gem 'active_data'
gem 'active_model_serializers', '~> 0.8.0'
gem 'ancestry'
gem 'ahoy_matey'
gem 'auto_strip_attributes', '~> 2.0'
gem 'bootstrap-sass', '~> 3.4.1'
gem 'chewy', '~> 7.2.0'
gem 'coffee-rails', '~> 4.1'
gem 'csv_shaper'
gem 'dalli'
gem 'devise', '~> 4.7'
gem 'enumerize'
gem 'friendly_id', '~> 5.0'
gem 'font-awesome-rails'
gem 'geocoder'
gem 'google-api-client', '~> 0.9'
gem 'haml-rails'
gem 'i18n', '1.10.0'
gem 'jquery-rails', '~> 4.0'
gem 'kaminari', '~> 1.1'
gem 'listen'
gem 'kgio'
gem 'memcachier'
gem 'nokogiri', '~> 1.15.0'
gem 'pg'
gem 'puma'
gem 'pundit'
gem 'rack-cors', require: 'rack/cors'
gem 'rack-rewrite', '~> 1.5.0'
gem 'redcarpet', '~> 3.5'
gem 'rails', '~> 7.0.0'
gem 'sass-rails', '~> 6.0.0'
gem 'select2-rails', '~> 4.0.3'
gem 'simplemde-rails', '~> 1.11', '>= 1.11.2'
gem 'smarter_csv'
gem 'sentry-raven'
gem "sprockets-rails"
gem 'uglifier', '>= 1.3.0'
gem 'shrine', '~> 3.0'
gem 'aws-sdk-s3', '~> 1.14'
gem 'image_processing', '~> 1.10'
gem 'uppy-s3_multipart', '>= 0.3.2'
gem 'marcel'
gem 'fastimage'
gem 'jsbundling-rails'
gem 'turbolinks', '~> 5.2.0'

group :test, :development do
  gem 'bullet'
  gem 'byebug'
  gem 'factory_bot_rails'
  gem 'faker', git: 'https://github.com/faker-ruby/faker.git', ref: '91950218dd39119e420ca431fc9fae09b53986c7'
  gem 'rspec-its'
  gem 'rspec-rails', '~> 4.0'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner-active_record'
  gem 'poltergeist'
  gem 'rails-controller-testing'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', git: 'https://github.com/thoughtbot/shoulda-matchers.git', ref: '206d2dae4c3bad8b6450a1762d06d315c35801aa'
  gem 'simplecov', require: false
  gem 'webmock'
end

group :development do
  gem 'foreman'
  gem 'better_errors', '>= 0.7.2'
  gem 'binding_of_caller'
  gem 'bummr', git: 'https://github.com/lpender/bummr.git', ref: '8eb0e4e984eeb2971a97a7259c5ce7592c30ebab'
  gem 'derailed'
  gem 'flamegraph'
  gem 'letter_opener'
  gem 'pry-rails'
  gem 'rack-mini-profiler'
  gem 'stackprof'
end

gem "tailwindcss-rails", "~> 2.0"
