source 'https://rubygems.org'

ruby '2.5.3'
gem 'active_data'
gem 'active_model_serializers', '~> 0.8.0'
gem 'ancestry'
gem 'auto_strip_attributes', '~> 2.0'
gem 'bootstrap-sass', '~> 3.4.1'
gem 'chewy'
gem 'coffee-rails', '~> 4.1'
gem 'csv_shaper'
gem 'dalli'
gem 'devise', '~> 4.7'
gem 'enumerize'
gem 'figaro', '~> 1.0'
gem 'friendly_id', '~> 5.0'
gem 'geocoder'
gem 'haml-rails'
gem 'jquery-rails', '~> 4.0'
gem 'kaminari', '~> 1.1'
gem 'memcachier'
gem 'pg'
gem 'puma'
gem 'pundit'
gem 'rack-cache'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '~> 5.2.3'
gem 'sass-rails', '~> 6.0.0'
gem 'select2-rails', '~> 4.0.3'
gem 'simplemde-rails', '~> 1.11', '>= 1.11.2'
gem 'smarter_csv'
gem 'uglifier', '>= 1.3.0'
gem 'shrine', '~> 3.0'
gem 'aws-sdk-s3', '~> 1.14'
gem 'image_processing', '~> 1.10'
gem 'uppy-s3_multipart', '>= 0.3.2'
gem 'marcel'
gem 'fastimage'
gem 'webpacker', '~> 5.1', '>= 5.1.1'

group :test, :development do
  gem 'bullet'
  gem 'byebug'
  gem 'factory_bot_rails'
  gem 'rspec-its'
  gem 'rspec-rails', '~> 4.0'
end

group :test do
  gem 'capybara'
  gem 'chromedriver-helper'
  gem 'database_cleaner', '>= 1.0.0.RC1'
  gem 'haml_lint'
  gem 'poltergeist'
  gem 'rails-controller-testing'
  gem 'rubocop', '~> 0.52.1'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', git: 'https://github.com/thoughtbot/shoulda-matchers.git'
  gem 'simplecov', require: false
  gem 'webmock'
end

group :development do
  gem 'better_errors', '>= 0.7.2'
  gem 'binding_of_caller'
  gem 'bummr', git: 'https://github.com/lpender/bummr.git'
  gem 'derailed'
  gem 'flamegraph'
  gem 'letter_opener'
  gem 'pry-rails'
  gem 'meta_request'
  gem 'rack-mini-profiler'
  gem 'reek'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen'
  gem 'stackprof'
end
